thread-test/config/routes.rb
ThreadTest::Application.routes.draw do

  resources :time_getters

  get "home/index"
  get "home/inde"
  root :to => 'home#index'

end

thread-test/app/models/time_getter.rb
class TimeGetter < ActiveRecord::Base
end

thread-test/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

thread-test/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

thread-test/app/controllers/time_getters_controller.rb
class TimeGettersController < ApplicationController
  include CalcTest
  include AsaiVis
  before_action :set_time_getter, only: [:show, :edit, :update, :destroy]

  # GET /time_getters
  # GET /time_getters.json
  def index
    @time_getters = TimeGetter.all
    @calc =  calc(1,4)
    @array = getHtml
  end

  # GET /time_getters/1
  # GET /time_getters/1.json
  def show
  end

  # GET /time_getters/new
  def new
    @time_getter = TimeGetter.new
  end

  # GET /time_getters/1/edit
  def edit
  end

  # POST /time_getters
  # POST /time_getters.json
  def create
    @time_getter = TimeGetter.new(time_getter_params)

    respond_to do |format|
      if @time_getter.save
        format.html { redirect_to @time_getter, notice: 'Time getter was successfully created.' }
        format.json { render action: 'show', status: :created, location: @time_getter }
      else
        format.html { render action: 'new' }
        format.json { render json: @time_getter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /time_getters/1
  # PATCH/PUT /time_getters/1.json
  def update
    respond_to do |format|
      if @time_getter.update(time_getter_params)
        format.html { redirect_to @time_getter, notice: 'Time getter was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @time_getter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /time_getters/1
  # DELETE /time_getters/1.json
  def destroy
    @time_getter.destroy
    respond_to do |format|
      format.html { redirect_to time_getters_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_time_getter
      @time_getter = TimeGetter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def time_getter_params
      params.require(:time_getter).permit(:datetime, :html)
    end
end

thread-test/app/helpers/application_helper.rb
module ApplicationHelper
end

thread-test/app/helpers/home_helper.rb
module HomeHelper
end

thread-test/app/helpers/time_getters_helper.rb
module TimeGettersHelper
end

thread-test/app/views/time_getters/_form.html.erb
<%= form_for(@time_getter) do |f| %>
  <% if @time_getter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@time_getter.errors.count, "error") %> prohibited this time_getter from being saved:</h2>

      <ul>
      <% @time_getter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :datetime %><br>
    <%= f.datetime_select :datetime %>
  </div>
  <div class="field">
    <%= f.label :html %><br>
    <%= f.text_area :html %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

thread-test/app/views/time_getters/edit.html.erb
<h1>Editing time_getter</h1>

<%= render 'form' %>

<%= link_to 'Show', @time_getter %> |
<%= link_to 'Back', time_getters_path %>

thread-test/app/views/time_getters/index.html.erb
<h1>Listing time_getters</h1>

<table>
  <thead>
    <tr>
      <th>Datetime</th>
      <th>Html</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @time_getters.each do |time_getter| %>
      <tr>
        <td><%= time_getter.datetime %></td>
        <td><%= time_getter.html %></td>
        <td><%= link_to 'Show', time_getter %></td>
        <td><%= link_to 'Edit', edit_time_getter_path(time_getter) %></td>
        <td><%= link_to 'Destroy', time_getter, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>



<% @array.each do |array| %>
<%= array %> </br>
<% end %>


<%= link_to 'New Time getter', new_time_getter_path %>

thread-test/app/views/time_getters/new.html.erb
<h1>New time_getter</h1>

<%= render 'form' %>

<%= link_to 'Back', time_getters_path %>

thread-test/app/views/time_getters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Datetime:</strong>
  <%= @time_getter.datetime %>
</p>

<p>
  <strong>Html:</strong>
  <%= @time_getter.html %>
</p>

<%= link_to 'Edit', edit_time_getter_path(@time_getter) %> |
<%= link_to 'Back', time_getters_path %>